### ISSUE TITLE
train crash

### ISSUE THREAD

**Issue by guozj583** [Maclory/SPSR#13]
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main()
  File "train.py", line 134, in main
    model.test()
  File "/home/xxx/Repository/SR_project/SPSR/code/models/SPSR_model.py", line 388, in test
    self.fake_H_branch, self.fake_H, self.grad_LR = self.netG(self.var_L)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Repository/SR_project/SPSR/code/models/modules/architecture.py", line 191, in forward
    x_f_cat = self.f_block(x_f_cat)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Repository/SR_project/SPSR/code/models/modules/block.py", line 229, in forward
    out = self.RDB3(out)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxx/Repository/SR_project/SPSR/code/models/modules/block.py", line 206, in forward
    x5 = self.conv5(torch.cat((x, x1, x2, x3, x4), 1))
RuntimeError: CUDA out of memory. Tried to allocate 1.61 GiB (GPU 0; 10.73 GiB total capacity; 4.65 GiB already allocated; 1.46 GiB free; 3.77 GiB cached)

**Comment by Maclory** [comment]
Hi, the error is caused by the limitation of GPU memory. You can check the usage of your GPUs and experiment settings such as batchsize and input size to fix it.
