### ISSUE TITLE
Errors accur when using evaluation tool box

### ISSUE THREAD

**Issue by HarrysVision** [Maclory/SPSR#32]
Hi, when I using the evaluation tool box to test one of the benchmark datasets, an error accurred:

Traceback (most recent call last):
  File "evaluate_sr_results.py", line 99, in <module>
    LPIPS=CalLPIPS(j,k)
  File "evaluate_sr_results.py", line 56, in CalLPIPS
    dist = model.forward(imageA,imageB).detach().squeeze().numpy()
  File "G:\dissertation\New Papers\SPSR\SPSR-master\metrics\LPIPS\__init__.py", line 40, in forward
    return self.model.forward(target, pred)
  File "G:\dissertation\New Papers\SPSR\SPSR-master\metrics\LPIPS\dist_model.py", line 117, in forward
    return self.net.forward(in0, in1, retPerLayer=retPerLayer)
  File "G:\dissertation\New Papers\SPSR\SPSR-master\metrics\LPIPS\networks_basic.py", line 72, in forward
    diffs[kk] = (feats0[kk]-feats1[kk])**2
RuntimeError: The size of tensor a (170) must match the size of tensor b (169) at non-singleton dimension 2

I follow the instructions provided, and other datasets seems to work well( I tested on Set5, B100, etc.), why?

**Comment by Maclory** [comment]
Hi, the sizes of the SR image and the corresponding HR image may be different.  In general, the SR and HR image sizes should be a multiple of 4 since the upscaling factor is 4.
